const DEFAULT_TIMEOUT = 1692531200000000000;
export const PROJECTX_API_URL = import.meta.env.VITE_PROJECTX_API_URL;
export const LOCAL_API_URL = import.meta.env.VITE_PROJECTX_API_URL;

export { DEFAULT_TIMEOUT };
